//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasteBookEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class REF_COUNTRY
    {
        public int ID { get; set; }
        public string COUNTRY { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
